#ifndef EFF20_CMDS_H
#define EFF20_CMDS_H

#define	RD_ENABLE	0x00	// "ENABLE" BUTTONS (EDITOR/DME/GPI)
#define WR_ENABLE	0x80
#define RD_SYSINFO	0x10	// SYSTEM INFORMATION (SWITCHER VERSION/TIMEDATE)
#define WR_SYSINFO	0x90
#define RD_SYSSETUP	0x11	// SYSTEM SETUP
#define WR_SYSSETUP	0x91
#define RD_KEYER	0x13	// KEYER
#define WR_KEYER	0x93
#define RD_MATTE	0x16	// MATTE
#define WR_MATTE	0x96
#define RD_GPIIN	0x17	// GPIIN
#define WR_GPIIN	0x97

#endif
